### ISSUE TITLE
This is really useful

### ISSUE THREAD

**Issue by joeblew99** [rightscale/wstunnel#20]
My wife is a doctor and I have been running some apps web apps on the raspberry pi 3 at home.

This would mean that from her mobile she can reach the raspberry pi.

I can get ride of the aweful VPN stuff. I needed this because putting a box on the public internet is asking for  script kiddy attacks.

This might even work with let's encrypt.

The relay server that is sitting in the public cloud can host the front end, but tunnel all data web sockets through to the raspberry pi.

Have you though about authentication though ?
I was thinking of use public / private key pairs.
The mobile phone requests all transmit with the public key as part of the payload, and the relay server checks them against the private key on the raspberry pi. No private key is held on the cloud server.

Is this project still used by you guys in production ? Just wondering if bug fixes from me are likely to get attention ?
I plan to use the awesome Hypriot to run everything as docker containers on the raspberry pi.

**Comment by tve** [comment]
We are using this in production both as stand-alone process and within other services as a library. Bug fixes are welcome, the main issue with new code is that testing this stuff is a pain. I started this project before I really got into writing tests for everything, so the test coverage isn't there.

WRT authentication, yes, we have thought about it. At some level wstunnel is just a transport and the expectation is that the target web service does whatever auth it needs to do. Using long non-obvious tunnel tokens makes it very unlikely that anyone gets through the tunnel, but one shouldn't consider the tokens to be very secure because they can easily end up in bookmarks, search engines, etc if one is not careful.

It should be pretty easy to put nginx or equivalent in from of the public wstunnel server and use that to add auth and HTTPS. Since you're into docker, I use the jwilder/nginx-proxy with the jrcs/letsencrypt-nginx-proxy-companion sidecar successfully.

**Comment by joeblew99** [comment]
@tve thanks for replying to my questions. Really nice of you.

Regarding Proxy Server, i will use hypriot to run the docker stuff on my rasp pi. I tried it last night and was painless.
http://blog.hypriot.com/post/microservices-bliss-with-docker-and-traefik/

Regarding Auth, 
If i use Lets Encrypt on the cloud server, then the tokens will be embedded into some part of the Web socket headers, and because its TLS, they are secret. The only way she and her doctor friends can ever pair their mobile with the raspberrypi is to do it at our house on the local wifi. The pairing is simply copying the generated machine key to her mobile phone and storing it in the web sites local storage. 
User auth with JWT still applies and is used. 
Wil see how it goes :)

I wil stop bugging you as i am sure your supper busy though.

Thank you again for this great code and your advice.
